### ISSUE TITLE
Infinite loop when labeling an object and error in uploading in image

### ISSUE THREAD

**Issue by phoang7** [fidler-lab/polyrnn-pp-pytorch#17]
I changed the global folder to my image directory containing the required images in the polygon.js, but when running the frontend and backend I am not able to label an image nor upload a photo, there is an infinite loop for labeling and error message appears when a image is attempted to be uploaded. No output is produced on the terminal, except for on the frontend when refreshing the page. I've included the terminals below. 
![backend](https://user-images.githubusercontent.com/41241533/52511892-f66ea780-2bb6-11e9-9435-80810e6ca520.png)
![frontend](https://user-images.githubusercontent.com/41241533/52511894-fe2e4c00-2bb6-11e9-8b28-daa467adaad6.png)

Also I changed the globalFolder variable to be set to:
var globalFolder = '/home/myusername/Downloads/polyrnn-pp-pytorch/code/Tool/frontend/static/img'

**Comment by lipeiwang** [comment]
same error here.
I git the folder, and run the backend and frontend.
But I can not get any result after draw a bounding box on the pic.

**Comment by amlankar** [comment]
Hi @phoang7, @lipeiwang, I'm closing this and would ask to follow #14. I haven't been able to reproduce this bug yet, so any more details would be appreciated on that thread.  

I just posted my screenshot on #14 reproducing the instructions in the README and running on my personal laptop. For all the changes, I used a separate terminal, I hope that helps.
