### ISSUE TITLE
About evaluation of 'n_corrections'

### ISSUE THREAD

**Issue by zhiyong1997** [fidler-lab/polyrnn-pp-pytorch#23]
Hi, @amlankar. For some downstream usage, I'm trying to get the number of corrections when using the model to assist human annotation, which is exactly the evaluation metric mentioned in the paper. However, what I can only find is the function 'process_outputs' in 'generate_annotation.py', which simply assigns 0 to the value. Is the procedure of calculating the number of corrections included in the code? Can you provide it if not?

Thanks!

**Comment by amlankar** [comment]
We haven't made this available right now, and might not in the near future (due to other engagements). We'd be very welcome to a contribution if you'd like to implement it. The method is explained in the CVPR '17 paper, and I'm happy to explain in pseudocode if needed.
