### ISSUE TITLE
the orientation of the sequence

### ISSUE THREAD

**Issue by Jacoobr** [fidler-lab/polyrnn-pp-pytorch#24]
Hi, @amlankar , I don't understant that you said in your paper CVPR17: "Here, we fix the polygon to always follow the clockwise orientation,".But how you did it in your code?, In other words, How can you control the orientation to be clockwise always?   I looked into the `rnn_step` with `attention`  mechanism of your code like :
```
att_feats, att = self.attention(feats, rnn_state)
att_feats_bak, att_bak = self.attention(feats, rnn_state_back)
input_t = torch.cat((att_feats, v_prev2, v_prev1, v_first), dim=1)
```
Does the 'catination' order of 'v_prev2, v_prev2, v_first' make clockwise orientation?  Apprecaitive for your reply, thank U~.

**Comment by amlankar** [comment]
This is done in the data itself. In the data files we provide, all polygons are in a fixed orientation.

**Comment by Jacoobr** [comment]
I got it, thank U~.
