### ISSUE TITLE
I have an error in training my own data set

### ISSUE THREAD

**Issue by CSYslient** [fidler-lab/polyrnn-pp-pytorch#28]
hi, @amlankar , I got an error while training my own data set. It may be that my own data set has errors, but I can't find the error.Can you give me a standard format for the data set?
![1](https://user-images.githubusercontent.com/37856790/58784957-1ec35b80-8617-11e9-9786-91bc8b94d2f0.png)

**Comment by wenmengliu** [comment]
hi, @amlankar, I also feel confused about how to utilize this tool on my own dataset. I have one question about online learning for new domains annotation. In the paper, it mentioned about annotating the new dataset based on the trained model.  For my own dataset, it came from the aerial images taken by UAV.  I wanna annotate different categories in the aerial images. What is the standard format for my own dataset? Do I need to make my own dataset as the cityscapes.json? Thx!!!!!

**Comment by Flames60** [comment]
Hi, could you send the training code to me? It seems like they do not give the code any longer. 
I would really appreciate it.
