### ISSUE TITLE
Command for training the RL model.

### ISSUE THREAD

**Issue by finnthedawg** [fidler-lab/polyrnn-pp-pytorch#31]
The command for training the RL model is 
"python Scripts/train/train_rl.py --exp Experiments/mle.json --resume <optional_if_resuming_training>"

Why do we change the paths in rl.json and then train with the mle.json configuration. We are supposed to train the rl model with rl.json right?

**Comment by amlankar** [comment]
Oops, this is an error. You are correct, you should be training with rl.json

Thanks for bringing this up!

**Comment by Cosmic-Dust** [comment]
@finnthedawg Excuse me,How is the training and demonstration code obtained

**Comment by finnthedawg** [comment]
> @finnthedawg Excuse me,How is the training and demonstration code obtained

http://www.cs.toronto.edu/polyrnn/code_signup/

**Comment by Cosmic-Dust** [comment]
@finnthedawg 
Hello, what do I need to do after registration is complete, I don’t see the code.
![1](https://user-images.githubusercontent.com/46952068/62381667-8eee4f00-b57e-11e9-99f4-9e4d550fd93b.png)

**Comment by veeramallirajesh** [comment]
@finnthedawg @amlankar I have registered for the code using my university email id more than a week ago and I still did not receive any response back. Is there something else I need to do?
