### ISSUE TITLE
What is path_to_downloaded_annotation_file?

### ISSUE THREAD

**Issue by lily1128** [fidler-lab/polyrnn-pp-pytorch#34]
I downloaded the file but can't find the path_to_downloaded_annotation_file. What should it be?

**Comment by Flames60** [comment]
Hi, do you have the training code? I would appreciate it very much if you could send it to me. It seems like they are busy with CVPR.

My email is:
gongwei.bo@163.com

Thanks!

**Comment by lily1128** [comment]
Oh actually are you asking for the code? I can send it to you.

发自我的iPhone

**Comment by amlankar** [comment]
Lily, sharing code is a violation of our terms of usage, please make sure
you do not do this

**Comment by amlankar** [comment]
@Flames60 you need to sign up with your academic email so we can verify and share code

**Comment by lily1128** [comment]
Get it, haven’t sent yet, sorry about that!

发自我的iPhone

**Comment by Flames60** [comment]
> @Flames60 you need to sign up with your academic email so we can verify and share code

Oh I get the point, thanks for your reply.

**Comment by Flames60** [comment]
> Get it, haven’t sent yet, sorry about that! 发自我的iPhone
> […](#)
> 在 2019年10月28日，下午8:51，Amlan Kar ***@***.***> 写道： ﻿ Closed #34. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks very much !!!
