### ISSUE TITLE
Web demo not working

### ISSUE THREAD

**Issue by sarslancs** [fidler-lab/polyrnn-pp-pytorch#39]
I wanted to try out the annotation tool before setting it up locally, but the web demo hosted at http://www.cs.toronto.edu/~amlan/demo/ does not seem to work. I believe the problem is with the backend since I keep seeing the 3 dots forever (as in the ss below). 

<img width="1161" alt="Screenshot 2020-02-05 at 15 19 35" src="https://user-images.githubusercontent.com/9154315/73855178-96dbc400-482b-11ea-83ef-54186d956d56.png">

I looked for a contact link on the demo page itself, but couldn't find one, so apologies in advance if this is no place for demo-related issues.

**Comment by amlankar** [comment]
This has been fixed, thanks for letting us know!
