### ISSUE TITLE
What are 'xe_initializer' and 'encoder_reload'? Are they provided by you?

### ISSUE THREAD

**Issue by LetsGoFir** [fidler-lab/polyrnn-pp-pytorch#40]
They are in the config file of ggnn.

**Comment by amlankar** [comment]
Hey, yes, encoder_reload refers to the resnet_50 checkpoint, and xe_initializer (in context of ggnn) refers to the trained model from the evaluator phase

**Comment by LetsGoFir** [comment]
> Hey, yes, encoder_reload refers to the resnet_50 checkpoint, and xe_initializer (in context of ggnn) refers to the trained model from the evaluator phase

Thanks for you reply.
If I want to reproduce the best result in your paper, do I need to run the 4 train step sequentially(MLE->RL->Eval->GGNN),
or I can get it by only run the GGNN training without 'xe_initializer'?
