### ISSUE TITLE
Are the models you have supported in the code the model you get the results in the paper?

### ISSUE THREAD

**Issue by LetsGoFir** [fidler-lab/polyrnn-pp-pytorch#41]
I find that the epoch is very small, like 'ggnn_epoch8_step21000.pth', but the epochs you have set in the config is about 200.

**Comment by amlankar** [comment]
Hey, yes the models released with the code are in fact better than the ones reported in the paper. We have set epochs to 200, but usually stop training much earlier (early stopping)

**Comment by LetsGoFir** [comment]
Thanks
