### ISSUE TITLE
Just a query regarding 'ggnn_epoch5_step14000.pth'

### ISSUE THREAD

**Issue by abinjoabraham** [fidler-lab/polyrnn-pp-pytorch#7]
So to obtain this pytorch metagraph kinda thing did you trained just only one instance which included
MLE + Att + Evaluator + GGNN (Shared Encoder) ?? Or did you trained attention MLE + Att + Evaluator separately and incorporated with the GGNN .pth to obtain this final ggnn_epoch5_step14000.pth file? Sorry if this is a lame question. I didn't really gone completely through the training code :)

**Comment by amlankar** [comment]
We train the model in steps, first train with cross entropy. Initialize with this model and train with RL, then initialize with the RL model to train the evaluator, and GGNN. The process is documented in the README
