### ISSUE TITLE
Regarding the values passed again to the pytorch model for the corrected coordinates #21

### ISSUE THREAD

**Issue by abinjoabraham** [fidler-lab/polyrnn-pp-pytorch#9]
I was interested in the fixing method while testing the model. Especially about the variable 'instance['fwd_poly']'. I just initially thought this variable is the new value which is generated after the user does the correction interactively. But after printing this fwd_poly of instance it seems like some floating point numbers with values less than 100. If you don't mind can you elaborate how this fwd_poly is populated?

**Comment by amlankar** [comment]
Could you specify file/line number. Usually instance[key] comes from the data provider.

**Comment by abinjoabraham** [comment]
This is called exactly when we do the fixing of the coordinates or the correction of the coordinates. Goes to the fixing function right in the Tool.py script line number 77 on Tool.py file. I tried printing this instance['fwd_poly'] and I was wondering instead of image coordinates I saw some floating point numbers which are less than 100 with no decimal parts.

**Comment by amlankar** [comment]
'fwd_poly' comes from the Data Provider. You could search for 'fwd_poly' in DataProvider/cityscapes.py to see its origin.

**Comment by abinjoabraham** [comment]
@amlankar Thanks for your reply. That solves my query. :+1:
